### PR TITLE
Received achievements count bug fix

### LINKED ISSUE #159: Number of received achievements is not updated on the People Page
Feedback from Nikita:
> Я заметил что количество наград у людей обновляется только после перезахода в список людей

### PR DESCRIPTION
**Pull request by SavikPavel**
#159 fix
- Update received achievements count rollback from Cloud Function to batch update;
- Update received achievements count on Users page

### CODE REVIEW

File: src/lib/services/database/database_service.dart [hunk 1]
```diff
@@ -4,13 +4,15 @@ class DatabaseService {
   final _database = Firestore.instance;
 
   Future<void> batchUpdate(
-    Function(WriteBatch) f1,
-    Function(WriteBatch) f2,
-  ) {
+    void Function(WriteBatch) f1,
```
Comment (wcoder) [inline src/lib/services/database/database_service.dart:7]: What do you think about using list as an argument?
```dart
Future<void> batchUpdate(
  List<void Function(WriteBatch)> list
) {
  // ...
}
```

Comment (SavikPavel) [reply src/lib/services/database/database_service.dart]: Reworked
